development:
  adapter: postgresql
  encoding: unicode
  database: docket_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: docket_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: docket_production
  pool: 5
  password:
